# Generated by Django 4.2.4 on 2023-09-18 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('PID', models.AutoField(primary_key=True, serialize=False)),
                ('Fname', models.CharField(max_length=50)),
                ('Lname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('Procedure_Core', models.IntegerField(primary_key=True, serialize=False)),
                ('Procedure_Name', models.CharField(max_length=50)),
                ('Cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MidtermExam.person')),
                ('Specialty', models.CharField(max_length=50)),
            ],
            bases=('MidtermExam.person',),
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proceed', models.ManyToManyField(to='MidtermExam.procedure')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MidtermExam.person')),
                ('attending_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MidtermExam.doctor')),
            ],
            bases=('MidtermExam.person',),
        ),
        migrations.CreateModel(
            name='DocToProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeOfProcedure', models.TimeField()),
                ('DateOfProcedure', models.DateField()),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_done', to='MidtermExam.procedure')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MidtermExam.doctor')),
            ],
        ),
    ]
