# Generated by Django 4.2.4 on 2023-09-18 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MidtermExam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='person_patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MidtermExam.patient'),
        ),
    ]
