# Generated by Django 4.2.4 on 2023-09-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MidtermExam', '0004_alter_medicalhistory_person_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalhistory',
            name='person_patient',
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='person_patient',
            field=models.ManyToManyField(to='MidtermExam.patient'),
        ),
    ]
