# Generated by Django 4.2.4 on 2023-09-18 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MidtermExam', '0006_rename_person_patient_medicalhistory_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalhistory',
            name='patient',
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='MidtermExam.patient'),
        ),
    ]
