# Generated by Django 4.2.4 on 2023-09-18 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MidtermExam', '0007_remove_medicalhistory_patient_medicalhistory_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='person_ptr',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='person_ptr',
        ),
        migrations.AddField(
            model_name='doctor',
            name='Fname',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Lname',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='doctor',
            name='PID',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='Fname',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='Lname',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='PID',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MidtermExam.patient'),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
